version: '3.9'

services:
  dnsproxy:
    tty: true
    restart: always
    image: danxiaonuo/dnsproxy:latest
    container_name: dnsproxy
    hostname: dnsproxy
    cap_add:
     - ALL
    volumes:
      # dnsproxy配置目录
      - ./conf/dnsproxy/dnsproxy.conf:/etc/dnsproxy/dnsproxy:rw,cached
      - ./ssl:/ssl:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
    network_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
